version: "2.0"
services:
  mongo:
    image: mongo:3.4
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'password'

  gridfs:
    restart: always
    image: lloydzhou/nginx-gridfs
    ports:
      - "80:80"
    links:
      - mongo
    volumes:
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf

